- name: "Ensure configuration checkpoint"
  ios_config:
    parents: archive
    lines:
      - path {{ network_config.rollback.path }}{{ network_config.rollback.file }}
      - maximum 10
      - write-memory

- name: "Generate checkpoint"
  ios_command:
    commands:
      - archive config
