---
security_zones:
  - name: inside
    interfaces:
      - name: ge-0/0/1.0
        type: host-inbound-traffic
        services:
          - name: ping
          - name: telnet
          - name: snmp
          - name: traceroute
          - name: ssh
          - name: http
          - name: https
    address_books:
      - name: "host01-linux"
        ipv4: 10.1.2.99/32

  - name: inside
    interfaces:
      - name: ge-0/0/1.0
        type: host-inbound-traffic
        services:
          - name: ping
          - name: telnet
          - name: snmp
          - name: traceroute
          - name: http
          - name: https
          - name: wsman
          - name: wsmans
    address_books:
      - name: "host01-windows"
        ipv4: 10.1.2.98/32
