- hosts: all
  connection: local
  gather_facts: false

  vars:
    project_path: .

  tasks:

    - name: detect requirements.yml
      stat: path={{project_path|quote}}/roles/requirements.yml
      register: doesRequirementsExist

    - name: fetch galaxy roles from requirements.yml
      command: ansible-galaxy install -r requirements.yml -p {{project_path|quote}}/roles/ --force
      args:
        chdir: "{{project_path|quote}}/roles"
      when: doesRequirementsExist.stat.exists
