- name: "virtualserver.pool: Ensure state of pool"
  bigip_pool:
    server: "{{ provider.server | default(omit) }}"
    server_port: "{{ provider.server_port | default(omit) }}"
    user: "{{ provider.user | default(omit) }}"
    password: "{{ provider.password | default(omit) }}"
    validate_certs: "{{ provider.validate_certs | default(omit) }}"
    name: "{{ pool.name }}"
    state: "{{ pool.state | default(omit) }}"

- name: "virtualserver.pool: Ensure association between pool and virtualserver"
  bigip_virtual_server:
    server: "{{ provider.server | default(omit) }}"
    server_port: "{{ provider.server_port | default(omit) }}"
    user: "{{ provider.user | default(omit) }}"
    password: "{{ provider.password | default(omit) }}"
    validate_certs: "{{ provider.validate_certs | default(omit) }}"
    name: "{{ virtualserver.name }}"
    pool: "{{ pool.name }}"
    state: "{{ pool.state | default(omit) }}"

- include_tasks: virtualserver.pool.members.yml
