- name: "virtualserver: Ensure state of VirtualServer"
  bigip_virtual_server:
    server: "{{ provider.server | default(omit) }}"
    server_port: "{{ provider.server_port | default(omit) }}"
    user: "{{ provider.user | default(omit) }}"
    password: "{{ provider.password | default(omit) }}"
    validate_certs: "{{ provider.validate_certs | default(omit) }}"
    name: "{{ virtualserver.name }}"
    destination: "{{ virtualserver.destination | ipaddr('address') }}"
    port: "{{ virtualserver.port }}"
    snat: "{{ virtualserver.snat }}"
    state: "{{ virtualserver.state | default(omit) }}"

- include_tasks: virtualserver.pools.yml
