panos_nat_rules:
  - rule_name: "NATAllOut"
    snat_type: "dynamic-ip-and-port"
    snat_interface: "ethernet1/1"
    snat_address_type: "interface-address"
    destination_zone: "untrust"
    source_zone:
      - "trust"
    source_ip:
      - "any"
    destination_ip:
      - "any"