---
- name: "victorock.interfaces-ios"
  block:
    - name: "sanity"
      include_tasks: sanity.yml

    - name: "victorock.config-{{ ansible_network_os }}"
      include_role:
        name: "victorock.config-{{ ansible_network_os }}"
        tasks_from: checkpoint

    - name: "interfaces"
      include_tasks: interfaces.yml
      when: interfaces is defined

    - name: "interface"
      include_tasks: interface.yml
      when: interface is defined

    - name: "assemble"
      include_tasks: assemble.yml

    - name: "victorock.config-{{ ansible_network_os }}"
      include_role:
        name: "victorock.config-{{ ansible_network_os }}"
        tasks_from: push
      vars:
        network_config: "{{ interface_config }}"

    - name: "assert"
      include_tasks: assert.yml

  rescue:
    - name: " /!\\ ROLLBACK /!\\"
      include_role:
        name: "victorock.config-{{ ansible_network_os }}"
        tasks_from: rollback

  always:
    - include_role:
        name: "victorock.config-{{ ansible_network_os }}"
        tasks_from: save

    - include_role:
        name: "victorock.config-{{ ansible_network_os }}"
        tasks_from: backup
