- name: "interface: Ensure state of layer1 parameters"
  junos_interface:
    name: "{{ interface.name }}"
    enabled: "{{ interface.enabled | default(omit) }}"
    duplex: "{{ interface.duplex | default(omit) }}"
    speed: "{{ interface.speed | default(omit) }}"
    mtu: "{{ interface.mtu | default(omit) }}"
    description: "{{ interface.description | default(omit) }}"
    active: "{{ interface.active | default(omit) }}"

- include_tasks: "interface.{{ interface.type | default('route') }}.yml"
