virtualservers:
  - name: http-pool
    destination: 10.1.1.200
    port: 80
    snat: automap
    state: present
    pools:
      - name: http-pool
        port: 80
        state: present
        members:
          - name: 10.1.2.99
            port: 80
            state: present
  - name: http-pool-8080
    destination: 10.1.1.200
    port: 8080
    snat: automap
    state: present
    pools:
      - name: http-pool-8080
        port: 8080
        state: present
        members:
          - name: 10.1.2.99
            port: 8080
            state: present
