- name: "Device Facts"
  hosts: all
  connection: network_cli
  gather_facts: no

  tasks:
    - name: Gather ios facts
      ios_facts:

    - name: "Print platform facts"
      debug:
        msg: |
          Serial: {{ ansible_facts.net_serialnum }}
          Model: {{ ansible_facts.net_model }}
          Mem (Total): {{ ansible_facts.net_memtotal_mb }}
          Mem (Free): {{ ansible_facts.net_memfree_mb }}

    - name: "Assert that the device has enough resources"
      assert:
        that: ansible_facts.net_memfree_mb|int > 512
        msg: /!\ Low Free Resources /!\
